baseURL = "https://park.is/"
languageCode = "en-us"
title = "Ye Joo Park's Blog"
theme = "park-blog-theme"
paginate = 5
googleAnalytics = "UA-170280017-1"

[taxonomies]
category = "categories"

[markup]

  [markup.highlight]
  style = "monokailight"

  [markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "GitHub"
  weight = 0
  identifier = "GitHub"
  url = "http://github.com/subwaymatch"